on run {id_, newName, newPriority, newCompleted, newDueDate}
  tell application "Reminders"
    set output to ""
    set myReminder to 1st reminder whose id is id_
    set name of myReminder to newName
    set priority of myReminder to newPriority
    set completed of myReminder to newCompleted
    if (newDueDate is equal to "missing value")
        delete due date of myReminder
    else
      set due date of myReminder to date newDueDate
    end if
  end tell
end run
